#!/bin/bash
#BSUB -J resnet_ood_metrics
#BSUB -q p1
#BSUB -R "select[gpu80gb]"
#BSUB -R "span[hosts=1]"
#BSUB -gpu "num=1:mode=exclusive_process"
#BSUB -n 4
#BSUB -W 20:00
#BSUB -R "rusage[mem=32GB]"
#BSUB -o logs/%J.out
#BSUB -e logs/%J.err

module load python3/3.11.4 cuda/12.3.2 cudnn/v8.9.1.23-prod-cuda-12.X
source proj/bin/activate
export XLA_PYTHON_CLIENT_PREALLOCATE=false


# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type MAP --experiment CIFAR-10-OOD --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0  --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type MAP --experiment CIFAR-10-C --corruption fog --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0  --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type MAP --experiment CIFAR-10-C --corruption gaussian_blur --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0  --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type MAP --experiment CIFAR-10-C --corruption brightness --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0  --prior_precision 0.05

# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type MAP --experiment CIFAR-10-OOD --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1  --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type MAP --experiment CIFAR-10-C --corruption fog --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1  --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type MAP --experiment CIFAR-10-C --corruption gaussian_blur --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1  --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type MAP --experiment CIFAR-10-C --corruption brightness --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1  --prior_precision 0.05


# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type MAP --experiment CIFAR-10-OOD --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2  --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type MAP --experiment CIFAR-10-C --corruption fog --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2  --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type MAP --experiment CIFAR-10-C --corruption gaussian_blur --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2  --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type MAP --experiment CIFAR-10-C --corruption brightness --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2  --prior_precision 0.05

# python experiments/ood_metrics.py --dataset SVHN --model ResNet_small --posterior_type Projection --experiment SVHN-OOD --parameter_path ./checkpoints/SVHN/ResNet_small_SVHN_0_params --posterior_path ./checkpoints/posterior_samples/SVHN/ResNet_small/svhn_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0 --prior_precision 0.05
# python experiments/ood_metrics.py --dataset SVHN --model ResNet_small --posterior_type Projection --experiment SVHN-OOD --parameter_path ./checkpoints/SVHN/ResNet_small_SVHN_1_params --posterior_path ./checkpoints/posterior_samples/SVHN/ResNet_small/svhn_samples_1_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1 --prior_precision 0.05
# python experiments/ood_metrics.py --dataset SVHN --model ResNet_small --posterior_type Projection --experiment SVHN-OOD --parameter_path ./checkpoints/SVHN/ResNet_small_SVHN_2_params --posterior_path ./checkpoints/posterior_samples/SVHN/ResNet_small/svhn_samples_2_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2 --prior_precision 0.05

# # python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Projection --experiment CIFAR-10-OOD --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_perturb_2iters_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name perturb2iters --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Projection --experiment CIFAR-10-OOD --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0 --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Projection --experiment CIFAR-10-C --corruption fog --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0  --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Projection --experiment CIFAR-10-C --corruption gaussian_blur --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0  --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Projection --experiment CIFAR-10-C --corruption brightness --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0  --prior_precision 0.05


# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Projection --experiment CIFAR-10-OOD --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_1_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1  --prior_precision 0.05 --refinement
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Projection --experiment CIFAR-10-C --corruption fog --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_1_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1  --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Projection --experiment CIFAR-10-C --corruption gaussian_blur --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_1_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1  --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Projection --experiment CIFAR-10-C --corruption brightness --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_1_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1  --prior_precision 0.05


# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Projection --experiment CIFAR-10-OOD --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_2_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2  --prior_precision 0.05 --refinement
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Projection --experiment CIFAR-10-C --corruption fog --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_2_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2  --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Projection --experiment CIFAR-10-C --corruption gaussian_blur --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_2_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2  --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Projection --experiment CIFAR-10-C --corruption brightness --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/posterior_samples/CIFAR-10/ResNet_small/cifar_samples_2_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2  --prior_precision 0.05


# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Loss-Kernel --experiment CIFAR-10-OOD --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/loss_kernel_samples/CIFAR-10/ResNet_small/cifar_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0 --prior_precision 0.05 --refinement
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Loss-Kernel --experiment CIFAR-10-C --corruption fog --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/loss_kernel_samples/CIFAR-10/ResNet_small/cifar_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0 --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Loss-Kernel --experiment CIFAR-10-C --corruption gaussian_blur --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/loss_kernel_samples/CIFAR-10/ResNet_small/cifar_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0 --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Loss-Kernel --experiment CIFAR-10-C --corruption brightness --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/loss_kernel_samples/CIFAR-10/ResNet_small/cifar_samples_0_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0 --prior_precision 0.05


# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Loss-Kernel --experiment CIFAR-10-OOD --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/loss_kernel_samples/CIFAR-10/ResNet_small/cifar_samples_1_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1 --prior_precision 0.05 --refinement
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Loss-Kernel --experiment CIFAR-10-C --corruption fog --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/loss_kernel_samples/CIFAR-10/ResNet_small/cifar_samples_1_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1 --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Loss-Kernel --experiment CIFAR-10-C --corruption gaussian_blur --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/loss_kernel_samples/CIFAR-10/ResNet_small/cifar_samples_1_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1 --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Loss-Kernel --experiment CIFAR-10-C --corruption brightness --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/loss_kernel_samples/CIFAR-10/ResNet_small/cifar_samples_1_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1 --prior_precision 0.05


# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Loss-Kernel --experiment CIFAR-10-OOD --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/loss_kernel_samples/CIFAR-10/ResNet_small/cifar_samples_2_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2 --prior_precision 0.05 --refinement
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Loss-Kernel --experiment CIFAR-10-C --corruption fog --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/loss_kernel_samples/CIFAR-10/ResNet_small/cifar_samples_2_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2 --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Loss-Kernel --experiment CIFAR-10-C --corruption gaussian_blur --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/loss_kernel_samples/CIFAR-10/ResNet_small/cifar_samples_2_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2 --prior_precision 0.05
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Loss-Kernel --experiment CIFAR-10-C --corruption brightness --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/loss_kernel_samples/CIFAR-10/ResNet_small/cifar_samples_2_sample_seed_0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2 --prior_precision 0.05

python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type SWAG --experiment CIFAR-10-OOD --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/baseline_samples/SWAG/CIFAR-10/ResNet_small/swag_0_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0 --prior_precision 1.0
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type SWAG --experiment CIFAR-10-C --corruption fog --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/baseline_samples/SWAG/CIFAR-10/ResNet_small/swag_0_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0 --prior_precision 1.0
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type SWAG --experiment CIFAR-10-C --corruption gaussian_blur --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/baseline_samples/SWAG/CIFAR-10/ResNet_small/swag_0_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0 --prior_precision 1.0
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type SWAG --experiment CIFAR-10-C --corruption brightness --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/baseline_samples/SWAG/CIFAR-10/ResNet_small/swag_0_seed_0_prec1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0 --prior_precision 1.0


python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type SWAG --experiment CIFAR-10-OOD --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/baseline_samples/SWAG/CIFAR-10/ResNet_small/swag_1_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1 --prior_precision 1.0
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type SWAG --experiment CIFAR-10-C --corruption fog --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/baseline_samples/SWAG/CIFAR-10/ResNet_small/swag_1_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1 --prior_precision 1.0
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type SWAG --experiment CIFAR-10-C --corruption gaussian_blur --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/baseline_samples/SWAG/CIFAR-10/ResNet_small/swag_1_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1 --prior_precision 1.0
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type SWAG --experiment CIFAR-10-C --corruption brightness --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/baseline_samples/SWAG/CIFAR-10/ResNet_small/swag_1_seed_0_prec1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1 --prior_precision 1.0


python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type SWAG --experiment CIFAR-10-OOD --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/baseline_samples/SWAG/CIFAR-10/ResNet_small/swag_2_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2 --prior_precision 1.0
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type SWAG --experiment CIFAR-10-C --corruption fog --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/baseline_samples/SWAG/CIFAR-10/ResNet_small/swag_2_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2 --prior_precision 1.0
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type SWAG --experiment CIFAR-10-C --corruption gaussian_blur --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/baseline_samples/SWAG/CIFAR-10/ResNet_small/swag_2_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2 --prior_precision 1.0
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type SWAG --experiment CIFAR-10-C --corruption brightness --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/baseline_samples/SWAG/CIFAR-10/ResNet_small/swag_2_seed_0_prec1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2 --prior_precision 1.0

# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Subnetwork --experiment CIFAR-10-OOD --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/baseline_samples/Subnetwork/CIFAR-10/ResNet_small/last_layer_0_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0 --prior_precision 1.0
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Subnetwork --experiment CIFAR-10-C --corruption fog --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/baseline_samples/Subnetwork/CIFAR-10/ResNet_small/last_layer_0_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0 --prior_precision 1.0
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Subnetwork --experiment CIFAR-10-C --corruption gaussian_blur --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/baseline_samples/Subnetwork/CIFAR-10/ResNet_small/last_layer_0_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0 --prior_precision 1.0
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Subnetwork --experiment CIFAR-10-C --corruption brightness --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/baseline_samples/Subnetwork/CIFAR-10/ResNet_small/last_layer_0_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0 --prior_precision 1.0


# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Subnetwork --experiment CIFAR-10-OOD --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/baseline_samples/Subnetwork/CIFAR-10/ResNet_small/last_layer_1_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1 --prior_precision 1.0
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Subnetwork --experiment CIFAR-10-C --corruption fog --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/baseline_samples/Subnetwork/CIFAR-10/ResNet_small/last_layer_1_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1 --prior_precision 1.0
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Subnetwork --experiment CIFAR-10-C --corruption gaussian_blur --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/baseline_samples/Subnetwork/CIFAR-10/ResNet_small/last_layer_1_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1 --prior_precision 1.0
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Subnetwork --experiment CIFAR-10-C --corruption brightness --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/baseline_samples/Subnetwork/CIFAR-10/ResNet_small/last_layer_1_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1 --prior_precision 1.0


# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Subnetwork --experiment CIFAR-10-OOD --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/baseline_samples/Subnetwork/CIFAR-10/ResNet_small/last_layer_2_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2 --prior_precision 1.0
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Subnetwork --experiment CIFAR-10-C --corruption fog --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/baseline_samples/Subnetwork/CIFAR-10/ResNet_small/last_layer_2_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2 --prior_precision 1.0
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Subnetwork --experiment CIFAR-10-C --corruption gaussian_blur --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/baseline_samples/Subnetwork/CIFAR-10/ResNet_small/last_layer_2_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2 --prior_precision 1.0
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Subnetwork --experiment CIFAR-10-C --corruption brightness --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/baseline_samples/Subnetwork/CIFAR-10/ResNet_small/last_layer_2_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2 --prior_precision 1.0


python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Exact_Diag --experiment CIFAR-10-OOD --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/baseline_samples/Exact_Diag/CIFAR-10/ResNet_small/diag_0_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0 --prior_precision 0.005
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Exact_Diag --experiment CIFAR-10-C --corruption fog --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/baseline_samples/Exact_Diag/CIFAR-10/ResNet_small/diag_0_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0 --prior_precision 0.005
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Exact_Diag --experiment CIFAR-10-C --corruption gaussian_blur --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/baseline_samples/Exact_Diag/CIFAR-10/ResNet_small/diag_0_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0 --prior_precision 0.005
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Exact_Diag --experiment CIFAR-10-C --corruption brightness --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_0_params --posterior_path ./checkpoints/baseline_samples/Exact_Diag/CIFAR-10/ResNet_small/diag_0_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 0 --prior_precision 1.0


python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Exact_Diag --experiment CIFAR-10-OOD --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/baseline_samples/Exact_Diag/CIFAR-10/ResNet_small/diag_1_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1 --prior_precision 0.005
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Exact_Diag --experiment CIFAR-10-C --corruption fog --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/baseline_samples/Exact_Diag/CIFAR-10/ResNet_small/diag_1_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1 --prior_precision 0.005
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Exact_Diag --experiment CIFAR-10-C --corruption gaussian_blur --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/baseline_samples/Exact_Diag/CIFAR-10/ResNet_small/diag_1_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1 --prior_precision 0.005
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Exact_Diag --experiment CIFAR-10-C --corruption brightness --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_1_params --posterior_path ./checkpoints/baseline_samples/Exact_Diag/CIFAR-10/ResNet_small/diag_1_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 1 --prior_precision 1.0


python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Exact_Diag --experiment CIFAR-10-OOD --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/baseline_samples/Exact_Diag/CIFAR-10/ResNet_small/diag_2_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2 --prior_precision 0.005
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Exact_Diag --experiment CIFAR-10-C --corruption fog --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/baseline_samples/Exact_Diag/CIFAR-10/ResNet_small/diag_2_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2 --prior_precision 0.005
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Exact_Diag --experiment CIFAR-10-C --corruption gaussian_blur --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/baseline_samples/Exact_Diag/CIFAR-10/ResNet_small/diag_2_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2 --prior_precision 0.005
# python experiments/ood_metrics.py --dataset CIFAR-10 --model ResNet_small --posterior_type Exact_Diag --experiment CIFAR-10-C --corruption brightness --parameter_path ./checkpoints/CIFAR10/ResNet_small_CIFAR-10_2_params --posterior_path ./checkpoints/baseline_samples/Exact_Diag/CIFAR-10/ResNet_small/diag_2_seed_0_prec_1.0_params --ood_batch_size 128 --num_samples_per_class 500 --run_name 2 --prior_precision 1.0


